services:
  - docker

sudo: required

language: c

env:
  - STEP: format
  - BUILDENV:
  - BUILDENV: ubuntu-14.04
  - BUILDENV: debian-jessie
  - BUILDENV: debian-stretch
  - BUILDENV: debian-sid

matrix:
  fast_finish: true
  exclude:
    - compiler: clang
      env: STEP=format
    - compiler: clang
      env: BUILDENV=ubuntu-14.04
    - compiler: clang
      env: BUILDENV=debian-jessie
    - compiler: clang
      env: BUILDENV=debian-stretch
    - compiler: clang
      env: BUILDENV=debian-sid

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libnl-3-200 libnl-route-3-200 liblldpctl-dev libnl-3-dev libnl-route-3-dev libnl-genl-3-dev clang-format-3.6 libbsd-dev

script:
  - if [ "$STEP" = 'format' ]; then make format; git --no-pager diff -- src; if [ `git --no-pager diff -- src| wc -l` != 0 ]; then exit 1; fi; fi
  - if [ "$STEP" = '' -a "$BUILDENV" = '' ]; then make test; exit $?; fi
  - if [ "$BUILDENV" != '' ]; then make test/envs/$BUILDENV.stamp; exit $?; fi
