services:
  - docker

sudo: required

language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libnl-3-200 libnl-route-3-200 liblldpctl-dev libpthread-stubs0-dev libnl-3-dev libnl-route-3-dev libnl-genl-3-dev

script:
  - make test
